<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /**
         * 创建promise对象
         */
        /*
        console.log('1');
        const promise = new Promise(function(resolve, reject){ 
            console.log('2');
        })
        console.log('3')
        */
       /*
       查看promise的状态
        const promise = new Promise(function(resolve, reject){ 
            // resolve()
            reject()
        })
        console.log(promise)
        */

        /*
        状态切换
        const promise = new Promise(function(resolve, reject){
            // resolve()
            reject()
        })

        promise.then(function(){
            console.log('执行成功1')
        })
        promise.then(function(){
            console.log('执行成功2')
        })

        promise.catch(function(){
            console.log('执行失败1')
        })
        promise.catch(function(){
            console.log('执行失败2')
        })
        */

        /*
        then接收两个参数 
        */
       /*
        const promise = new Promise(function(resolve, reject){
            // resolve()
            reject()
        })
        promise.then(function(){
            console.log('执行成功')
        }, function(){
            console.log('执行失败')
        })
        */
        
        /*
         * then 传递参数
         * catch 
         */
        /*
        const promise = new Promise(function(resolve, reject){
            resolve('123')
            reject('456')
        })
        promise.then(function(param){
            console.log('执行成功---' + param)
        }).catch(function(param){
            console.log('执行失败---' + param)
        })

        const promise2 = new Promise(function(resolve, reject){
            resolve('123')
            // reject('456')
        })
        function success(param) {
            console.log('执行成功---' + param)
        }
        function failture(param) {
            console.log('执行失败---' + param)
        }
        // 这两种写法一样，同样有效。
        // promise2.then(success, failture)
        promise2.then(success).catch(failture)
         */

         /*
        const promise = new Promise(function(resolve, reject){
            resolve()  //执行成功1 执行成功2
            // reject()  //执行失败1 执行失败2
        })

        promise.then(function(){
            console.log('执行成功1')
        }).catch(function(){
            console.log('执行失败1')
        })
        promise.then(function(){
            console.log('执行成功2')
        }).catch(function(){
            console.log('执行失败2')
        })
        */

        /*
        // then 方法和 catch 方法每次执行之后都会返回一个新的promise对象
        const promise = new Promise(function(resolve, reject){
            resolve()
            // reject()
        })
        const promise2 = promise.then(function(){
            console.log('执行成功')
        }).catch(function(){
            console.log('执行失败')
        })
        console.log(promise2)
        console.log(promise == promise2)
        */

        /*
        // 在 then 方法或者 catch 方法中返回值，会传递给新promise对象的then方法。需要注意的是，无论是 resolve 还是 reject 触发的状态改变，都会传递给下一个promise 的 then 方法。
        
        const promise = new Promise(function(resolve, reject){
            // resolve()
            reject()
        })
        const promise2 = promise.then(function(){
            console.log('执行成功1')
            return '2222'
        }).catch(function(){
            console.log('执行失败')
            return '3333'
        })

        promise2.then(function(param){
            console.log('执行成功2----' + param)
        }).catch(function(param){
            console.log('执行失败2----' + param)
        })
        */

        // const promise = new Promise(function(resolve, reject){
        //     reject()
        // })

        // const promise2 = new Promise(function(resolve, reject){
        //     reject('222')
        // })

        // const promise3 = promise.then(function(param){
        //     console.log('执行成功1---' + param)
        //     return promise2
        // }).catch(function(param){
        //     console.log('执行失败1---' + param)
        // })

        // promise3.then(function(param){
        //     console.log('执行成功3---' + param)
        // }).catch(function(param){
        //     console.log('执行失败3---' + param)
        // })
        
        let promise = new Promise(function (resolve, reject) {
        // resolve(); // 将状态修改为成功
        reject(); // 将状态修改为失败
    });
    // promise.then(function () {
    //     console.log("成功");
    // }).catch(function () {
    //     console.log("失败");
    // });

    // promise.then(function () {
    //     console.log("成功");
    // });
    // promise.catch(function () {
    //     console.log("失败");
    // });


    // promise.then(function () {
    //     console.log("成功");
    //     abc
    // }).catch(function (e) {
    //     console.log("失败", e);
    // });


    </script>
</body>
</html>